version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volume para persistência dos dados

volumes:
  mysql_data:  # Definição do volume
